name: ClickEdit
version: 1.2
description: Edit signs with a click!
author: bobacadodl
main: com.bobacadodl.ClickEdit.ClickEdit
depend: [ProtocolLib]
commands:
  clickedit:
    description: Edit the sign you are looking at.